### ISSUE TITLE
src subdirectory not part of this repo

### ISSUE THREAD

**Issue by voxmenthe** [cambridge-mlg/arch_uncert#1]
Great work! Apparently you have not included the main "src" subdirectory as part of the repo. I assume this is not intentional?

**Comment by JamesAllingham** [comment]
Hey @voxmenthe! Thanks for catching this. It was certainly not intended. It turns out that the GitHub upload feature breaks if you have empty files (like`__init__.py`) which prevented `src` and some of the files in `experiments` from being uploaded. It should all be fixed now though!
